ignore:
- ".*proofnetwork/*amqp*" # not really possible to verify by unit-tests without mocking rabbitmq server
- ".*proofnetwork/amqp*" # not really possible to verify by unit-tests without mocking rabbitmq server
- "**/*restapi*" # are verified by other modules. Real coverage can be seen in proof repo

coverage:
  range: 60..95
  round: down
  precision: 2

codecov:
  branch: develop
