#ifndef PROOFCORE_GLOBAL_H
#define PROOFCORE_GLOBAL_H

#ifdef PROOF_CORE_LIB
#  define PROOF_CORE_EXPORT Q_DECL_EXPORT
#else
#  define PROOF_CORE_EXPORT Q_DECL_IMPORT
#endif

#endif // PROOFCORE_GLOBAL_H
