#ifndef PROOFNETWORK_GLOBAL_H
#define PROOFNETWORK_GLOBAL_H

#ifdef PROOF_NETWORK_LIB
#  define PROOF_NETWORK_EXPORT Q_DECL_EXPORT
#else
#  define PROOF_NETWORK_EXPORT Q_DECL_IMPORT
#endif

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(proofNetworkLog)
Q_DECLARE_LOGGING_CATEGORY(proofNetworkCommonLog)

#endif // PROOFNETWORK_GLOBAL_H
